export const PERMISSIONS = {
  DEPARTMENTS_READ: 'organization.departments.read',
  DEPARTMENTS_CREATE: 'organization.departments.create',
  DEPARTMENTS_UPDATE: 'organization.departments.update',
  DEPARTMENTS_DELETE: 'organization.departments.delete',
  DESIGNATIONS_READ: 'organization.designations.read',
  DESIGNATIONS_CREATE: 'organization.designations.create',
  DESIGNATIONS_UPDATE: 'organization.designations.update',
  DESIGNATIONS_DELETE: 'organization.designations.delete',
  EMPLOYEES_READ: 'organization.employees.read',
  EMPLOYEES_REPORTS_READ: 'organization.employees.reports.read',
  EMPLOYEES_SELF_READ: 'organization.employees.self.read',
  EMPLOYEES_CREATE: 'organization.employees.create',
  EMPLOYEES_UPDATE: 'organization.employees.update',
  EMPLOYEES_LIFECYCLE: 'organization.employees.lifecycle',
  IMPORTS_READ: 'organization.imports.read',
  IMPORTS_CREATE: 'organization.imports.create',
  USERS_READ: 'identity.users.read',
  USERS_INVITE: 'identity.users.invite',
  USERS_ROLES_UPDATE: 'identity.users.roles.update',
  USERS_STATUS_UPDATE: 'identity.users.status.update',
  ROLES_READ: 'identity.roles.read',
  ROLES_CREATE: 'identity.roles.create',
  ROLES_UPDATE: 'identity.roles.update',
  ROLES_DELETE: 'identity.roles.delete',
  SETTINGS_READ: 'workspace.settings.read',
  SETTINGS_UPDATE: 'workspace.settings.update',
  DASHBOARD_ADMIN_READ: 'workspace.dashboard.admin.read',
  MODULES_READ: 'workspace.modules.read',
  MOBILE_RUNTIME_READ: 'mobile.runtime.read',
  BILLING_SUBSCRIPTION_READ: 'billing.subscription.read',
  BILLING_SUBSCRIPTION_MANAGE: 'billing.subscription.manage',
  BILLING_PROFILE_MANAGE: 'billing.profile.manage',
  BILLING_INVOICES_READ: 'billing.invoices.read',
  BILLING_PAYMENT_METHODS_MANAGE: 'billing.payment-methods.manage',
  ATTENDANCE_CONFIG_MANAGE: 'attendance.config.manage',
  ATTENDANCE_CONFIG_READ: 'attendance.config.read',
  ATTENDANCE_OFFICES_READ: 'attendance.offices.read',
  ATTENDANCE_OFFICES_MANAGE: 'attendance.offices.manage',
  ATTENDANCE_POLICIES_READ: 'attendance.policies.read',
  ATTENDANCE_POLICIES_MANAGE: 'attendance.policies.manage',
  ATTENDANCE_SHIFTS_READ: 'attendance.shifts.read',
  ATTENDANCE_SHIFTS_MANAGE: 'attendance.shifts.manage',
  ATTENDANCE_ROSTERS_READ: 'attendance.rosters.read',
  ATTENDANCE_ROSTERS_MANAGE: 'attendance.rosters.manage',
  ATTENDANCE_HOLIDAYS_READ: 'attendance.holidays.read',
  ATTENDANCE_HOLIDAYS_MANAGE: 'attendance.holidays.manage',
  ATTENDANCE_RECORDS_READ: 'attendance.records.read',
  ATTENDANCE_RECORDS_SELF_READ: 'attendance.records.self.read',
  ATTENDANCE_EXCEPTIONS_READ: 'attendance.exceptions.read',
  ATTENDANCE_EXCEPTIONS_MANAGE: 'attendance.exceptions.manage',
  ATTENDANCE_APPROVALS_MANAGE: 'attendance.approvals.manage',
  ATTENDANCE_REPORTS_READ: 'attendance.reports.read',
  ATTENDANCE_DEVICES_READ: 'attendance.devices.read',
  ATTENDANCE_DEVICES_MANAGE: 'attendance.devices.manage',
  ATTENDANCE_BIOMETRICS_READ: 'attendance.biometrics.read',
  ATTENDANCE_BIOMETRICS_MANAGE: 'attendance.biometrics.manage',
  ATTENDANCE_VERIFICATION_READ: 'attendance.verification.read',
  ATTENDANCE_ALERT_RULES_MANAGE: 'attendance.alert-rules.manage',
  ATTENDANCE_SECURITY_ALERTS_READ: 'attendance.security-alerts.read',
  ATTENDANCE_SECURITY_ALERTS_MANAGE: 'attendance.security-alerts.manage',
  ATTENDANCE_FIELD_LIVE_READ: 'attendance.field.live.read',
  ATTENDANCE_FIELD_ROUTES_READ: 'attendance.field.routes.read',
  REGULARIZATIONS_SELF: 'attendance.regularizations.self',
  REGULARIZATIONS_MANAGE: 'attendance.regularizations.manage',
  NOTIFICATIONS_SELF: 'notifications.self',
  ATTENDANCE_REPORTS_GENERATE: 'attendance.reports.generate',
  ATTENDANCE_PAYROLL_LOCK_MANAGE: 'attendance.payroll-lock.manage',
  LEAVE_SELF: 'leave.self',
  LEAVE_APPROVE: 'leave.approve',
  LEAVE_MANAGE: 'leave.manage',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const DEFAULT_ROLE_PERMISSIONS: Record<
  string,
  readonly PermissionKey[]
> = {
  BUSINESS_ADMIN: ALL_PERMISSIONS,
  HR_ADMIN: ALL_PERMISSIONS.filter(
    (permission) =>
      !permission.startsWith('billing.') &&
      permission !== PERMISSIONS.DASHBOARD_ADMIN_READ,
  ),
  MANAGER: [
    PERMISSIONS.EMPLOYEES_REPORTS_READ,
    PERMISSIONS.EMPLOYEES_SELF_READ,
    PERMISSIONS.ATTENDANCE_RECORDS_READ,
    PERMISSIONS.ATTENDANCE_RECORDS_SELF_READ,
    PERMISSIONS.ATTENDANCE_APPROVALS_MANAGE,
    PERMISSIONS.ATTENDANCE_DEVICES_READ,
    PERMISSIONS.ATTENDANCE_SECURITY_ALERTS_READ,
    PERMISSIONS.ATTENDANCE_FIELD_LIVE_READ,
    PERMISSIONS.ATTENDANCE_FIELD_ROUTES_READ,
    PERMISSIONS.REGULARIZATIONS_SELF,
    PERMISSIONS.NOTIFICATIONS_SELF,
    PERMISSIONS.LEAVE_SELF,
    PERMISSIONS.LEAVE_APPROVE,
  ],
  EMPLOYEE: [
    PERMISSIONS.EMPLOYEES_SELF_READ,
    PERMISSIONS.ATTENDANCE_RECORDS_SELF_READ,
    PERMISSIONS.MOBILE_RUNTIME_READ,
    PERMISSIONS.REGULARIZATIONS_SELF,
    PERMISSIONS.NOTIFICATIONS_SELF,
    PERMISSIONS.LEAVE_SELF,
  ],
};
