export {
  assertMatchingPlaceholders,
  isSupportedLocale,
  localeFallbackChain,
  LOCALE_REGISTRY,
  normalizeEnabledLanguages,
  PUBLIC_LANGUAGES,
  publicLanguageForLocale,
  regionalLocaleForCountry,
  REQUIRED_LOCALIZATION_NAMESPACES,
  resolveCatalogLocale,
  SUPPORTED_LOCALES,
  type PublicLanguage,
  type SupportedLocale,
} from './localization.constants';
