"use client";

import { CalendarDays, Check, Clock3, MapPin, Plus, ShieldCheck, Upload } from "lucide-react";
import { useEffect, useState } from "react";
import { apiClient } from "@/lib/api-client";
import { AdminPage, EmptyState, ErrorState, Field, LoadingState, Panel, PrimaryButton, inputClass } from "./page-primitives";

type Office = { id: string; officeName: string; latitude: string; longitude: string; radiusMeters: number; timezone?: string; egressIps: string[]; wifiSsids: string[]; _count?: { assignments: number; holidays: number } };
type PolicyAssignment = { id?: string; scope: "TENANT_DEFAULT" | "DEPARTMENT" | "EMPLOYEE"; deptId?: string | null; employeeId?: string | null };
type Policy = { id: string; name: string; lateAfterMinutes: number; halfDayAfterMinutes: number; minimumWorkMinutes: number; overtimeAfterMinutes: number; requireFaceMatch: boolean; requireRegisteredDevice: boolean; requireGeofence: boolean; maxOfflineSyncHours: number; maxFaceAttempts: number; assignments: PolicyAssignment[] };
type Shift = { id: string; name: string; startTime: string; endTime: string; isOvernight: boolean };
type Roster = { id: string; rosterDate: string; employee: { fullName: string; employeeCode: string }; shift: Shift };
type Employee = { id: string; fullName: string; employeeCode: string };
type Department = { id: string; name: string };
type Holiday = { id: string; holidayName: string; holidayDate: string; officeLocationId?: string; office?: Office };

export function OfficesView() {
  const [data, setData] = useState<Office[] | null>(null); const [employees, setEmployees] = useState<Employee[]>([]); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Office | null>(null); const [assigning, setAssigning] = useState<Office | null>(null); const [assignedIds, setAssignedIds] = useState<string[]>([]); const [primaryIds, setPrimaryIds] = useState<string[]>([]);
  const [form, setForm] = useState({ officeName: "", latitude: "19.0760", longitude: "72.8777", radiusMeters: "150", timezone: "Asia/Kolkata", egressIps: "", wifiSsids: "" });
  const load = () => Promise.all([apiClient.get("/offices"), apiClient.get("/employees?limit=100")]).then(([offices, employeeResult]) => { setData(offices.data.data); setEmployees(employeeResult.data.data); }).catch(() => setError("Office locations could not be loaded."));
  useEffect(() => { void load(); }, []);
  async function saveOffice() { setError(""); const payload = { officeName: form.officeName, latitude: Number(form.latitude), longitude: Number(form.longitude), radiusMeters: Number(form.radiusMeters), timezone: form.timezone, egressIps: form.egressIps.split(",").map(trim).filter(Boolean), wifiSsids: form.wifiSsids.split(",").map(trim).filter(Boolean) }; await (editing ? apiClient.patch(`/offices/${editing.id}`, payload) : apiClient.post("/offices", payload)).then(() => { setOpen(false); setEditing(null); load(); }).catch(() => setError("Office could not be saved. Check the geofence, network values, and references.")); }
  function openCreate() { setEditing(null); setForm({ officeName: "", latitude: "19.0760", longitude: "72.8777", radiusMeters: "150", timezone: "Asia/Kolkata", egressIps: "", wifiSsids: "" }); setOpen(true); }
  function openEdit(office: Office) { setEditing(office); setForm({ officeName: office.officeName, latitude: String(office.latitude), longitude: String(office.longitude), radiusMeters: String(office.radiusMeters), timezone: office.timezone ?? "", egressIps: office.egressIps.join(", "), wifiSsids: office.wifiSsids.join(", ") }); setOpen(true); }
  async function removeOffice() { if (!editing || !window.confirm(`Delete ${editing.officeName}?`)) return; await apiClient.delete(`/offices/${editing.id}`).then(() => { setOpen(false); setEditing(null); load(); }).catch(() => setError("Office cannot be deleted while assignments, holidays, or attendance evidence reference it.")); }
  async function openAssignments(office: Office) { setError(""); try { const result = await apiClient.get(`/offices/${office.id}/employees`); const rows = result.data.data as Array<{ employeeId: string; isPrimary: boolean }>; setAssignedIds(rows.map((row) => row.employeeId)); setPrimaryIds(rows.filter((row) => row.isPrimary).map((row) => row.employeeId)); setAssigning(office); } catch { setError("Office assignments could not be loaded."); } }
  async function saveAssignments() { if (!assigning) return; try { await apiClient.put(`/offices/${assigning.id}/employees`, { employeeIds: assignedIds, primaryEmployeeIds: primaryIds.filter((id) => assignedIds.includes(id)) }); setAssigning(null); await load(); } catch { setError("Office assignments could not be saved."); } }
  return <AdminPage title="Office Locations & Geofences" description="Control where employees may securely record attendance." action={<PrimaryButton onClick={openCreate}><Plus className="size-4" />Add office</PrimaryButton>}>
    {error && <ErrorState message={error} />}{!data ? <LoadingState /> : <div className="grid gap-6 xl:grid-cols-[1fr_420px]"><Panel className="overflow-hidden"><div className="grid grid-cols-[1fr_100px_90px_130px] border-b border-[#e4e1ee] bg-[#f5f2ff] px-6 py-3 text-xs font-bold uppercase tracking-wider text-[#777587]"><span>Office</span><span>Employees</span><span>Radius</span><span>Action</span></div>{data.length ? data.map((office) => <div key={office.id} className="grid grid-cols-[1fr_100px_90px_130px] items-center border-b border-[#e4e1ee] px-6 py-5 last:border-0"><div><div className="font-semibold">{office.officeName}</div><div className="mt-1 text-xs text-[#777587]">{office.timezone || "Tenant timezone"} · {(office.egressIps as string[]).length} trusted networks</div></div><span className="text-sm">{office._count?.assignments ?? 0}</span><span className="text-sm">{office.radiusMeters} m</span><div className="flex gap-3"><button className="text-left text-xs font-semibold text-[#3525cd]" onClick={() => openAssignments(office)}>Assign</button><button className="text-left text-xs font-semibold text-[#3525cd]" onClick={() => openEdit(office)}>Edit</button></div></div>) : <EmptyState title="No offices yet" body="Add an office to configure its circular geofence and network allow-list." />}</Panel><OfficeMap offices={data} /></div>}
    {open && <Dialog title={editing ? "Edit office" : "Add office"} onClose={() => { setOpen(false); setEditing(null); }}><div className="grid gap-4"><Field label="Office name"><input autoFocus className={inputClass} value={form.officeName} onChange={(e) => setForm({ ...form, officeName: e.target.value })} /></Field><div className="grid grid-cols-2 gap-4"><Field label="Latitude"><input className={inputClass} value={form.latitude} onChange={(e) => setForm({ ...form, latitude: e.target.value })} /></Field><Field label="Longitude"><input className={inputClass} value={form.longitude} onChange={(e) => setForm({ ...form, longitude: e.target.value })} /></Field></div><Field label="Radius in meters"><input type="number" className={inputClass} value={form.radiusMeters} onChange={(e) => setForm({ ...form, radiusMeters: e.target.value })} /></Field><Field label="Timezone"><input className={inputClass} value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })} /></Field><Field label="Egress IPs or CIDRs"><input className={inputClass} placeholder="203.0.113.10, 10.0.0.0/24" value={form.egressIps} onChange={(e) => setForm({ ...form, egressIps: e.target.value })} /></Field><Field label="Advisory Wi-Fi SSIDs"><input className={inputClass} value={form.wifiSsids} onChange={(e) => setForm({ ...form, wifiSsids: e.target.value })} /></Field><div className="flex gap-3">{editing && <button className="h-11 rounded-xl border border-[#ba1a1a] px-4 text-sm font-semibold text-[#ba1a1a]" onClick={removeOffice}>Delete</button>}<PrimaryButton className="flex-1" onClick={saveOffice}>Save office</PrimaryButton></div></div></Dialog>}
    {assigning && <Dialog title={`Assign employees · ${assigning.officeName}`} onClose={() => setAssigning(null)}><div className="grid max-h-96 gap-2 overflow-auto">{employees.map((employee) => <div key={employee.id} className="grid grid-cols-[1fr_auto] items-center rounded-lg bg-[#f5f2ff] p-3"><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={assignedIds.includes(employee.id)} onChange={(event) => { setAssignedIds((current) => event.target.checked ? [...current, employee.id] : current.filter((id) => id !== employee.id)); if (!event.target.checked) setPrimaryIds((current) => current.filter((id) => id !== employee.id)); }} /><span><strong>{employee.fullName}</strong><span className="block text-xs text-[#777587]">{employee.employeeCode}</span></span></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" disabled={!assignedIds.includes(employee.id)} checked={primaryIds.includes(employee.id)} onChange={(event) => setPrimaryIds((current) => event.target.checked ? [...current, employee.id] : current.filter((id) => id !== employee.id))} />Primary</label></div>)}</div><PrimaryButton className="mt-5 w-full" onClick={saveAssignments}>Save assignments</PrimaryButton></Dialog>}
  </AdminPage>;
}

export function PoliciesView() {
  const [data, setData] = useState<Policy[] | null>(null); const [departments, setDepartments] = useState<Department[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [editing, setEditing] = useState<Policy | null>(null); const [ruleEditing, setRuleEditing] = useState<Policy | null>(null); const [ruleForm, setRuleForm] = useState({ name: "", lateAfterMinutes: 15, halfDayAfterMinutes: 240, minimumWorkMinutes: 480, overtimeAfterMinutes: 540, maxOfflineSyncHours: 48, maxFaceAttempts: 3, requireGeofence: true, requireRegisteredDevice: true, requireFaceMatch: false }); const [assignments, setAssignments] = useState<PolicyAssignment[]>([]); const [assignmentForm, setAssignmentForm] = useState<{ scope: PolicyAssignment["scope"]; targetId: string }>({ scope: "TENANT_DEFAULT", targetId: "" });
  const load = () => Promise.all([apiClient.get("/attendance-policies"), apiClient.get("/departments"), apiClient.get("/employees?limit=100")]).then(([policies, departmentResult, employeeResult]) => { setData(policies.data.data); setDepartments(departmentResult.data.data); setEmployees(employeeResult.data.data); }).catch(() => setError("Policies could not be loaded.")); useEffect(() => { void load(); }, []);
  async function create() { await apiClient.post("/attendance-policies", { name }).then(() => { setOpen(false); setName(""); load(); }).catch(() => setError("Policy could not be created.")); }
  function addAssignment() { const next: PolicyAssignment = assignmentForm.scope === "TENANT_DEFAULT" ? { scope: "TENANT_DEFAULT" } : assignmentForm.scope === "DEPARTMENT" ? { scope: "DEPARTMENT", deptId: assignmentForm.targetId } : { scope: "EMPLOYEE", employeeId: assignmentForm.targetId }; const key = assignmentKey(next); if (!assignmentForm.targetId && assignmentForm.scope !== "TENANT_DEFAULT") return; if (!assignments.some((item) => assignmentKey(item) === key)) setAssignments((current) => [...current, next]); }
  async function saveAssignments() { if (!editing) return; try { await apiClient.put(`/attendance-policies/${editing.id}/assignments`, { assignments: assignments.map(({ scope, deptId, employeeId }) => ({ scope, ...(deptId ? { deptId } : {}), ...(employeeId ? { employeeId } : {}) })) }); setEditing(null); await load(); } catch { setError("Policy assignments conflict with an existing scope or target."); } }
  function openRuleEditor(policy: Policy) { setRuleEditing(policy); setRuleForm({ name: policy.name, lateAfterMinutes: policy.lateAfterMinutes, halfDayAfterMinutes: policy.halfDayAfterMinutes, minimumWorkMinutes: policy.minimumWorkMinutes, overtimeAfterMinutes: policy.overtimeAfterMinutes, maxOfflineSyncHours: policy.maxOfflineSyncHours, maxFaceAttempts: policy.maxFaceAttempts, requireGeofence: policy.requireGeofence, requireRegisteredDevice: policy.requireRegisteredDevice, requireFaceMatch: policy.requireFaceMatch }); }
  async function saveRules() { if (!ruleEditing) return; await apiClient.patch(`/attendance-policies/${ruleEditing.id}`, ruleForm).then(() => { setRuleEditing(null); load(); }).catch(() => setError("Policy rules could not be saved. Review the thresholds.")); }
  async function removePolicy() { if (!ruleEditing || !window.confirm(`Delete ${ruleEditing.name}?`)) return; await apiClient.delete(`/attendance-policies/${ruleEditing.id}`).then(() => { setRuleEditing(null); load(); }).catch(() => setError("Assigned policies cannot be deleted.")); }
  return <AdminPage title="Attendance Policies" description="Define verification and work-time rules, then assign by employee, department or tenant default." action={<PrimaryButton onClick={() => setOpen(true)}><Plus className="size-4" />Create policy</PrimaryButton>}>
    {error && <ErrorState message={error} />}{!data ? <LoadingState /> : <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{data.map((policy) => <Panel key={policy.id} className="p-6"><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-xl bg-[#e2dfff] text-[#3525cd]"><ShieldCheck /></div><span className="rounded-full bg-[#7cf994]/35 px-3 py-1 text-xs font-semibold text-[#005320]">{policy.assignments.length} assignments</span></div><h2 className="mt-5 text-xl font-semibold">{policy.name}</h2><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Metric label="Late after" value={`${policy.lateAfterMinutes} min`} /><Metric label="Half day" value={`${policy.halfDayAfterMinutes} min`} /><Metric label="Minimum work" value={`${policy.minimumWorkMinutes} min`} /><Metric label="Overtime" value={`${policy.overtimeAfterMinutes} min`} /></div><div className="mt-5 flex flex-wrap gap-2 text-[11px]">{policy.requireGeofence && <Tag>Geofence</Tag>}{policy.requireRegisteredDevice && <Tag>Device</Tag>}{policy.requireFaceMatch && <Tag>Face match</Tag>}</div><div className="mt-5 flex gap-4"><button className="text-sm font-semibold text-[#3525cd]" onClick={() => openRuleEditor(policy)}>Edit rules</button><button className="text-sm font-semibold text-[#3525cd]" onClick={() => { setEditing(policy); setAssignments(policy.assignments); }}>Manage assignments</button></div></Panel>)}{!data.length && <Panel className="lg:col-span-2 xl:col-span-3"><EmptyState title="No policies" body="Create a policy and assign one tenant default before attendance begins." /></Panel>}</div>}
    {open && <Dialog title="Create attendance policy" onClose={() => setOpen(false)}><Field label="Policy name"><input autoFocus className={inputClass} value={name} onChange={(e) => setName(e.target.value)} /></Field><div className="mt-5 rounded-xl bg-[#f5f2ff] p-4 text-sm text-[#464555]">New policies start with secure default thresholds and can be refined after creation.</div><PrimaryButton className="mt-5 w-full" onClick={create}>Create policy</PrimaryButton></Dialog>}
    {editing && <Dialog title={`Assignments · ${editing.name}`} onClose={() => setEditing(null)}><div className="grid gap-3">{assignments.map((assignment) => <div key={assignmentKey(assignment)} className="flex items-center justify-between rounded-lg bg-[#f5f2ff] p-3 text-sm"><span>{assignmentLabel(assignment, departments, employees)}</span><button className="text-xs font-semibold text-[#ba1a1a]" onClick={() => setAssignments((current) => current.filter((item) => assignmentKey(item) !== assignmentKey(assignment)))}>Remove</button></div>)}</div><div className="mt-5 grid gap-3 rounded-xl border border-[#e4e1ee] p-4"><Field label="Scope"><select className={inputClass} value={assignmentForm.scope} onChange={(event) => setAssignmentForm({ scope: event.target.value as PolicyAssignment["scope"], targetId: "" })}><option value="TENANT_DEFAULT">Tenant default</option><option value="DEPARTMENT">Department</option><option value="EMPLOYEE">Employee</option></select></Field>{assignmentForm.scope === "DEPARTMENT" && <Field label="Department"><select className={inputClass} value={assignmentForm.targetId} onChange={(event) => setAssignmentForm({ ...assignmentForm, targetId: event.target.value })}><option value="">Select department</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></Field>}{assignmentForm.scope === "EMPLOYEE" && <Field label="Employee"><select className={inputClass} value={assignmentForm.targetId} onChange={(event) => setAssignmentForm({ ...assignmentForm, targetId: event.target.value })}><option value="">Select employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select></Field>}<button className="h-10 rounded-lg border border-[#3525cd] text-sm font-semibold text-[#3525cd]" onClick={addAssignment}>Add assignment</button></div><PrimaryButton className="mt-5 w-full" onClick={saveAssignments}>Save assignments</PrimaryButton></Dialog>}
    {ruleEditing && <Dialog title="Edit policy rules" onClose={() => setRuleEditing(null)}><div className="grid gap-4"><Field label="Policy name"><input className={inputClass} value={ruleForm.name} onChange={(event) => setRuleForm({ ...ruleForm, name: event.target.value })} /></Field><div className="grid grid-cols-2 gap-3">{(["lateAfterMinutes", "halfDayAfterMinutes", "minimumWorkMinutes", "overtimeAfterMinutes", "maxOfflineSyncHours", "maxFaceAttempts"] as const).map((key) => <Field key={key} label={key.replaceAll(/([A-Z])/g, " $1")}><input type="number" className={inputClass} value={ruleForm[key]} onChange={(event) => setRuleForm({ ...ruleForm, [key]: Number(event.target.value) })} /></Field>)}</div>{(["requireGeofence", "requireRegisteredDevice", "requireFaceMatch"] as const).map((key) => <label key={key} className="flex items-center gap-3 rounded-lg bg-[#f5f2ff] p-3 text-sm"><input type="checkbox" checked={ruleForm[key]} onChange={(event) => setRuleForm({ ...ruleForm, [key]: event.target.checked })} />{key.replaceAll(/([A-Z])/g, " $1")}</label>)}<div className="flex gap-3"><button className="h-11 rounded-xl border border-[#ba1a1a] px-4 text-sm font-semibold text-[#ba1a1a]" onClick={removePolicy}>Delete</button><PrimaryButton className="flex-1" onClick={saveRules}>Save rules</PrimaryButton></div></div></Dialog>}
  </AdminPage>;
}

export function ShiftsView() {
  const [data, setData] = useState<Shift[] | null>(null); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Shift | null>(null); const [form, setForm] = useState({ name: "", startTime: "09:00", endTime: "18:00" });
  const load = () => apiClient.get("/shifts").then(({ data }) => setData(data.data)).catch(() => setError("Shifts could not be loaded.")); useEffect(() => { void load(); }, []);
  async function saveShift() { await (editing ? apiClient.patch(`/shifts/${editing.id}`, form) : apiClient.post("/shifts", form)).then(() => { setOpen(false); setEditing(null); load(); }).catch(() => setError("Shift could not be saved.")); }
  function openCreate() { setEditing(null); setForm({ name: "", startTime: "09:00", endTime: "18:00" }); setOpen(true); }
  function openEdit(shift: Shift) { setEditing(shift); setForm({ name: shift.name, startTime: shift.startTime, endTime: shift.endTime }); setOpen(true); }
  async function removeShift() { if (!editing || !window.confirm(`Delete ${editing.name}?`)) return; await apiClient.delete(`/shifts/${editing.id}`).then(() => { setOpen(false); setEditing(null); load(); }).catch(() => setError("Shift is referenced by employees, rosters, or attendance records.")); }
  return <AdminPage title="Shifts Management" description="Create day and overnight shifts with deterministic date attribution." action={<PrimaryButton onClick={openCreate}><Plus className="size-4" />Add new shift</PrimaryButton>}>
    {error && <ErrorState message={error} />}{!data ? <LoadingState /> : <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{data.map((shift) => <Panel key={shift.id} className="p-6"><div className="flex items-center justify-between"><div className="grid size-11 place-items-center rounded-xl bg-[#e2dfff] text-[#3525cd]"><Clock3 /></div>{shift.isOvernight && <span className="rounded-full bg-[#ffdcc3] px-3 py-1 text-xs font-semibold text-[#6e3900]">Overnight</span>}</div><h2 className="mt-5 text-lg font-semibold">{shift.name}</h2><div className="mt-5 flex items-center gap-4"><strong className="text-2xl">{shift.startTime}</strong><span className="h-1 flex-1 rounded-full bg-gradient-to-r from-[#3525cd] to-[#7cf994]" /><strong className="text-2xl">{shift.endTime}</strong></div><button className="mt-5 text-sm font-semibold text-[#3525cd]" onClick={() => openEdit(shift)}>Edit shift</button></Panel>)}</div>}
    {open && <Dialog title={editing ? "Edit shift" : "Add new shift"} onClose={() => { setOpen(false); setEditing(null); }}><div className="grid gap-4"><Field label="Shift name"><input className={inputClass} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><div className="grid grid-cols-2 gap-4"><Field label="Starts"><input type="time" className={inputClass} value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} /></Field><Field label="Ends"><input type="time" className={inputClass} value={form.endTime} onChange={(e) => setForm({ ...form, endTime: e.target.value })} /></Field></div><div className="flex gap-3">{editing && <button className="h-11 rounded-xl border border-[#ba1a1a] px-4 text-sm font-semibold text-[#ba1a1a]" onClick={removeShift}>Delete</button>}<PrimaryButton className="flex-1" onClick={saveShift}>Save shift</PrimaryButton></div></div></Dialog>}
  </AdminPage>;
}

export function RostersView() {
  const today = new Date(); const end = new Date(today.getTime() + 6 * 86_400_000); const iso = (date: Date) => date.toISOString().slice(0, 10);
  const [data, setData] = useState<Roster[] | null>(null); const [employees, setEmployees] = useState<Employee[]>([]); const [shifts, setShifts] = useState<Shift[]>([]); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [bulkOpen, setBulkOpen] = useState(false); const [form, setForm] = useState({ employeeId: "", shiftId: "", rosterDate: iso(today) }); const [bulkForm, setBulkForm] = useState({ employeeIds: [] as string[], shiftId: "", startDate: iso(today), endDate: iso(end) }); const [bulkResult, setBulkResult] = useState("");
  const load = () => Promise.all([apiClient.get(`/rosters?startDate=${iso(today)}&endDate=${iso(end)}`), apiClient.get("/employees?limit=100"), apiClient.get("/shifts")]).then(([rosters, employeeResult, shiftResult]) => { setData(rosters.data.data); setEmployees(employeeResult.data.data); setShifts(shiftResult.data.data); }).catch(() => setError("Roster planner could not be loaded."));
  // The initial planner range is intentionally fixed when this screen mounts.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []);
  async function create() { await apiClient.post("/rosters", form).then(() => { setOpen(false); load(); }).catch(() => setError("Roster assignment conflicts with an existing employee/date.")); }
  async function bulkAssign() { setError(""); try { const result = await apiClient.post("/rosters/bulk", bulkForm); const summary = result.data.data as { inserted: number; unchanged: number; errors: unknown[] }; setBulkResult(`${summary.inserted} assigned · ${summary.unchanged} unchanged · ${summary.errors.length} conflicts`); await load(); } catch { setError("Bulk roster assignment could not be completed."); } }
  async function removeRoster(roster: Roster) { if (!window.confirm(`Remove ${roster.shift.name} for ${roster.employee.fullName}?`)) return; await apiClient.delete(`/rosters/${roster.id}`).then(() => load()).catch(() => setError("Roster assignment could not be removed.")); }
  return <AdminPage title="Roster Planner" description="Plan the working week, bulk assign shifts and import validated CSV schedules." action={<div className="flex flex-wrap gap-3"><label className="inline-flex h-11 cursor-pointer items-center gap-2 rounded-xl border border-[#c7c4d8] bg-white px-4 text-sm font-semibold"><Upload className="size-4" />Import CSV<input type="file" accept=".csv" className="hidden" onChange={(event) => event.target.files?.[0] && uploadRoster(event.target.files[0], setError, load)} /></label><button className="h-11 rounded-xl border border-[#3525cd] bg-white px-4 text-sm font-semibold text-[#3525cd]" onClick={() => { setBulkOpen(true); setBulkResult(""); }}>Bulk assign</button><PrimaryButton onClick={() => setOpen(true)}><Plus className="size-4" />Assign shift</PrimaryButton></div>}>
    {error && <ErrorState message={error} />}{!data ? <LoadingState /> : <Panel className="overflow-auto"><div className="min-w-[850px]"><div className="grid grid-cols-[220px_repeat(7,1fr)] border-b border-[#e4e1ee] bg-[#f5f2ff]"><div className="p-4 text-xs font-bold uppercase text-[#777587]">Employee</div>{dateRange(today, end).map((date) => <div key={date.toISOString()} className="border-l border-[#e4e1ee] p-4 text-center text-xs font-bold"><div>{date.toLocaleDateString("en", { weekday: "short" })}</div><div className="text-[#777587]">{date.getDate()}</div></div>)}</div>{employees.map((employee) => <div key={employee.id} className="grid grid-cols-[220px_repeat(7,1fr)] border-b border-[#e4e1ee] last:border-0"><div className="p-4"><div className="font-semibold">{employee.fullName}</div><div className="text-xs text-[#777587]">{employee.employeeCode}</div></div>{dateRange(today, end).map((date) => { const roster = data.find((row) => row.employee.employeeCode === employee.employeeCode && row.rosterDate.slice(0, 10) === iso(date)); return <div key={date.toISOString()} className="grid min-h-16 place-items-center border-l border-[#e4e1ee] p-2">{roster ? <button title="Remove roster" className="rounded-lg bg-[#e2dfff] px-2 py-1 text-center text-xs font-semibold text-[#3323cc]" onClick={() => removeRoster(roster)}>{roster.shift.name}</button> : <span className="text-[#c7c4d8]">—</span>}</div>; })}</div>)}{!employees.length && <EmptyState title="No employees" body="Create employees before assigning weekly rosters." />}</div></Panel>}
    {open && <Dialog title="Assign shift" onClose={() => setOpen(false)}><div className="grid gap-4"><Field label="Employee"><select className={inputClass} value={form.employeeId} onChange={(e) => setForm({ ...form, employeeId: e.target.value })}><option value="">Select employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select></Field><Field label="Shift"><select className={inputClass} value={form.shiftId} onChange={(e) => setForm({ ...form, shiftId: e.target.value })}><option value="">Select shift</option>{shifts.map((shift) => <option key={shift.id} value={shift.id}>{shift.name}</option>)}</select></Field><Field label="Date"><input type="date" className={inputClass} value={form.rosterDate} onChange={(e) => setForm({ ...form, rosterDate: e.target.value })} /></Field><PrimaryButton onClick={create}>Assign shift</PrimaryButton></div></Dialog>}
    {bulkOpen && <Dialog title="Bulk assign shifts" onClose={() => setBulkOpen(false)}><div className="grid gap-4"><Field label="Shift"><select className={inputClass} value={bulkForm.shiftId} onChange={(event) => setBulkForm({ ...bulkForm, shiftId: event.target.value })}><option value="">Select shift</option>{shifts.map((shift) => <option key={shift.id} value={shift.id}>{shift.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Start date"><input type="date" className={inputClass} value={bulkForm.startDate} onChange={(event) => setBulkForm({ ...bulkForm, startDate: event.target.value })} /></Field><Field label="End date"><input type="date" className={inputClass} value={bulkForm.endDate} onChange={(event) => setBulkForm({ ...bulkForm, endDate: event.target.value })} /></Field></div><fieldset className="grid max-h-64 gap-2 overflow-auto"><legend className="mb-2 text-sm font-medium">Employees</legend>{employees.map((employee) => <label key={employee.id} className="flex items-center gap-3 rounded-lg bg-[#f5f2ff] p-3 text-sm"><input type="checkbox" checked={bulkForm.employeeIds.includes(employee.id)} onChange={(event) => setBulkForm((current) => ({ ...current, employeeIds: event.target.checked ? [...current.employeeIds, employee.id] : current.employeeIds.filter((id) => id !== employee.id) }))} />{employee.fullName}</label>)}</fieldset>{bulkResult && <div className="rounded-lg bg-[#d8f8df] p-3 text-sm text-[#005320]">{bulkResult}</div>}<PrimaryButton disabled={!bulkForm.shiftId || !bulkForm.employeeIds.length} onClick={bulkAssign}>Apply bulk roster</PrimaryButton></div></Dialog>}
  </AdminPage>;
}

export function HolidaysView() {
  const [data, setData] = useState<Holiday[] | null>(null); const [offices, setOffices] = useState<Office[]>([]); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Holiday | null>(null); const [form, setForm] = useState({ holidayName: "", holidayDate: "", officeLocationId: "" });
  const load = () => Promise.all([apiClient.get("/holidays"), apiClient.get("/offices")]).then(([holidays, officeResult]) => { setData(holidays.data.data); setOffices(officeResult.data.data); }).catch(() => setError("Holiday calendar could not be loaded.")); useEffect(() => { void load(); }, []);
  async function saveHoliday() { const payload = { holidayName: form.holidayName, holidayDate: form.holidayDate, ...(form.officeLocationId ? { officeLocationId: form.officeLocationId } : {}) }; await (editing ? apiClient.patch(`/holidays/${editing.id}`, payload) : apiClient.post("/holidays", payload)).then(() => { setOpen(false); setEditing(null); load(); }).catch(() => setError("Holiday already exists for this date and scope.")); }
  function openCreate() { setEditing(null); setForm({ holidayName: "", holidayDate: "", officeLocationId: "" }); setOpen(true); }
  function openEdit(holiday: Holiday) { setEditing(holiday); setForm({ holidayName: holiday.holidayName, holidayDate: holiday.holidayDate.slice(0, 10), officeLocationId: holiday.officeLocationId ?? "" }); setOpen(true); }
  async function removeHoliday() { if (!editing || !window.confirm(`Delete ${editing.holidayName}?`)) return; await apiClient.delete(`/holidays/${editing.id}`).then(() => { setOpen(false); setEditing(null); load(); }).catch(() => setError("Holiday could not be deleted.")); }
  return <AdminPage title="Holiday Calendar" description="Publish tenant-wide and office-specific holidays." action={<PrimaryButton onClick={openCreate}><Plus className="size-4" />Add holiday</PrimaryButton>}>
    {error && <ErrorState message={error} />}{!data ? <LoadingState /> : <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><Panel className="p-6"><div className="grid grid-cols-7 gap-2 text-center text-xs font-bold uppercase text-[#777587]">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <div key={day} className="p-2">{day}</div>)}</div><div className="mt-2 grid grid-cols-7 gap-2">{Array.from({ length: 35 }, (_, index) => { const day = index + 1; const holiday = data.find((item) => new Date(item.holidayDate).getUTCDate() === day); return <div key={day} className={`min-h-24 rounded-lg border p-2 ${holiday ? "border-[#c3c0ff] bg-[#e2dfff]" : "border-[#e4e1ee] bg-white"}`}><span className="text-xs font-semibold">{day}</span>{holiday && <button className="mt-2 block text-left text-xs font-semibold text-[#3323cc]" onClick={() => openEdit(holiday)}>{holiday.holidayName}</button>}</div>; })}</div></Panel><Panel className="p-6"><h2 className="font-semibold">Upcoming holidays</h2><div className="mt-4 grid gap-3">{data.map((holiday) => <button key={holiday.id} className="flex gap-3 rounded-lg bg-[#f5f2ff] p-3 text-left" onClick={() => openEdit(holiday)}><CalendarDays className="size-5 text-[#3525cd]" /><span><span className="block text-sm font-semibold">{holiday.holidayName}</span><span className="text-xs text-[#777587]">{new Date(holiday.holidayDate).toLocaleDateString()} · {holiday.office?.officeName ?? "All offices"}</span></span></button>)}</div></Panel></div>}
    {open && <Dialog title={editing ? "Edit holiday" : "Add holiday"} onClose={() => { setOpen(false); setEditing(null); }}><div className="grid gap-4"><Field label="Holiday name"><input className={inputClass} value={form.holidayName} onChange={(e) => setForm({ ...form, holidayName: e.target.value })} /></Field><Field label="Date"><input type="date" className={inputClass} value={form.holidayDate} onChange={(e) => setForm({ ...form, holidayDate: e.target.value })} /></Field><Field label="Scope"><select className={inputClass} value={form.officeLocationId} onChange={(e) => setForm({ ...form, officeLocationId: e.target.value })}><option value="">All offices</option>{offices.map((office) => <option key={office.id} value={office.id}>{office.officeName}</option>)}</select></Field><div className="flex gap-3">{editing && <button className="h-11 rounded-xl border border-[#ba1a1a] px-4 text-sm font-semibold text-[#ba1a1a]" onClick={removeHoliday}>Delete</button>}<PrimaryButton className="flex-1" onClick={saveHoliday}>Publish holiday</PrimaryButton></div></div></Dialog>}
  </AdminPage>;
}

function OfficeMap({ offices }: { offices: Office[] }) { return <Panel className="relative min-h-[420px] overflow-hidden bg-[#eae6f4]"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: "linear-gradient(#777587 1px, transparent 1px), linear-gradient(90deg, #777587 1px, transparent 1px)", backgroundSize: "32px 32px" }} />{offices.map((office, index) => <div key={office.id} className="absolute" style={{ left: `${25 + (index * 29) % 55}%`, top: `${25 + (index * 23) % 48}%` }}><div className="absolute left-1/2 top-1/2 size-28 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-[#3525cd]/35 bg-[#3525cd]/10" /><MapPin className="relative size-8 fill-[#3525cd] text-[#3525cd]" /></div>)}<div className="absolute bottom-4 left-4 rounded-lg bg-white/90 p-3 text-xs shadow"><strong>Map provider abstraction</strong><div className="text-[#777587]">Circular geofences shown without provider lock-in</div></div></Panel>; }
function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#1b1b24]/45 p-4"><div className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-2xl bg-white p-7 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={onClose} className="text-[#777587]">Close</button></div>{children}</div></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-[#f5f2ff] p-3"><div className="text-xs text-[#777587]">{label}</div><div className="mt-1 font-semibold">{value}</div></div>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-[#f0ecf9] px-3 py-1 text-[#464555]"><Check className="mr-1 inline size-3 text-[#006e2d]" />{children}</span>; }
function trim(value: string) { return value.trim(); }
function assignmentKey(assignment: PolicyAssignment) { return `${assignment.scope}:${assignment.deptId ?? assignment.employeeId ?? "default"}`; }
function assignmentLabel(assignment: PolicyAssignment, departments: Department[], employees: Employee[]) { if (assignment.scope === "TENANT_DEFAULT") return "Tenant default"; if (assignment.scope === "DEPARTMENT") return `Department · ${departments.find(({ id }) => id === assignment.deptId)?.name ?? "Unknown"}`; return `Employee · ${employees.find(({ id }) => id === assignment.employeeId)?.fullName ?? "Unknown"}`; }
function dateRange(start: Date, end: Date) { const result: Date[] = []; for (let cursor = new Date(start); cursor <= end; cursor = new Date(cursor.getTime() + 86_400_000)) result.push(cursor); return result; }
async function uploadRoster(file: File, setError: (message: string) => void, reload: () => void) { try { const presign = await apiClient.post("/rosters/imports/presign", { filename: file.name, contentType: file.type || "text/csv" }); await fetch(presign.data.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type || "text/csv" }, body: file }); await apiClient.post("/rosters/imports", { objectKey: presign.data.objectKey, originalFilename: file.name, idempotencyKey: `${file.name}-${file.size}-${file.lastModified}` }); reload(); } catch { setError("Roster CSV could not be uploaded or processed."); } }
