"use client";

import { Building2, FileUp, Plus, ShieldCheck, UserRoundPlus } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { apiClient } from "@/lib/api-client";
import { AdminPage, EmptyState, ErrorState, Field, LoadingState, Panel, PrimaryButton, inputClass } from "./page-primitives";

type Department = { id: string; name: string; parentDeptId?: string; children?: Department[]; _count?: { employees: number } };
type Designation = { id: string; name: string; employeeCount?: number };
type Employee = { id: string; employeeCode: string; fullName: string; phone?: string; workType: string; status: string; department?: Department; designation?: Designation };
type Role = { id: string; name: string; isSystem: boolean; permissionKeys?: string[]; assignedUsers?: number };
type User = { id: string; email: string; status: string; roles: Role[] };

export function OrganizationView() {
  const [departments, setDepartments] = useState<Department[] | null>(null); const [designations, setDesignations] = useState<Designation[]>([]); const [error, setError] = useState(""); const [departmentName, setDepartmentName] = useState(""); const [designationName, setDesignationName] = useState("");
  const load = () => Promise.all([apiClient.get("/departments?view=tree"), apiClient.get("/designations?limit=100")]).then(([departmentResult, designationResult]) => { setDepartments(departmentResult.data.data); setDesignations(designationResult.data.data); }).catch(() => setError("Organization structure could not be loaded.")); useEffect(() => { void load(); }, []);
  async function addDepartment() { await apiClient.post("/departments", { name: departmentName }).then(() => { setDepartmentName(""); load(); }).catch(() => setError("Department name already exists at this level.")); }
  async function addDesignation() { await apiClient.post("/designations", { name: designationName }).then(() => { setDesignationName(""); load(); }).catch(() => setError("Designation name already exists.")); }
  return <AdminPage title="Organization Builder" description="Build department hierarchy and maintain reusable designations.">{error && <ErrorState message={error} />}{!departments ? <LoadingState /> : <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Panel className="p-7"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">Departments</h2><Building2 className="text-[#3525cd]" /></div><div className="mb-5 flex gap-3"><input className={inputClass} placeholder="New department" value={departmentName} onChange={(e) => setDepartmentName(e.target.value)} /><PrimaryButton onClick={addDepartment}><Plus className="size-4" />Add</PrimaryButton></div><div className="grid gap-3">{departments.map((department) => <DepartmentNode key={department.id} department={department} />)}{!departments.length && <EmptyState title="No departments" body="Create your first department to start organizing employees." />}</div></Panel><Panel className="p-7"><h2 className="mb-6 text-xl font-semibold">Designations</h2><div className="mb-5 flex gap-3"><input className={inputClass} placeholder="New designation" value={designationName} onChange={(e) => setDesignationName(e.target.value)} /><PrimaryButton onClick={addDesignation}><Plus className="size-4" />Add</PrimaryButton></div><div className="grid gap-2">{designations.map((designation) => <div key={designation.id} className="flex items-center justify-between rounded-lg bg-[#f5f2ff] px-4 py-3"><span className="text-sm font-medium">{designation.name}</span><span className="text-xs text-[#777587]">{designation.employeeCount ?? 0} employees</span></div>)}</div></Panel></div>}</AdminPage>;
}

function DepartmentNode({ department, depth = 0 }: { department: Department; depth?: number }) { return <div><div className="flex items-center gap-3 rounded-lg border border-[#e4e1ee] bg-white px-4 py-3" style={{ marginLeft: depth * 24 }}><div className="grid size-8 place-items-center rounded-lg bg-[#e2dfff] text-[#3525cd]"><Building2 className="size-4" /></div><span className="font-medium">{department.name}</span></div>{department.children?.map((child) => <DepartmentNode key={child.id} department={child} depth={depth + 1} />)}</div>; }

export function EmployeesView() {
  const [data, setData] = useState<Employee[] | null>(null); const [error, setError] = useState("");
  useEffect(() => { apiClient.get("/employees?limit=100").then(({ data }) => setData(data.data)).catch(() => setError("Employees could not be loaded.")); }, []);
  return <AdminPage title="Employees" description="Manage workforce records, reporting relationships and lifecycle status." action={<Link href="/app/employees/new"><PrimaryButton><UserRoundPlus className="size-4" />Add employee</PrimaryButton></Link>}>{error && <ErrorState message={error} />}{!data ? <LoadingState /> : <Panel className="overflow-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f5f2ff] text-xs uppercase tracking-wider text-[#777587]"><tr><th className="px-6 py-4">Employee</th><th>Code</th><th>Department</th><th>Work type</th><th>Status</th></tr></thead><tbody>{data.map((employee) => <tr key={employee.id} className="border-t border-[#e4e1ee]"><td className="px-6 py-4"><div className="font-semibold">{employee.fullName}</div><div className="text-xs text-[#777587]">{employee.phone || "No phone"}</div></td><td>{employee.employeeCode}</td><td>{employee.department?.name || "—"}</td><td>{employee.workType}</td><td><span className="rounded-full bg-[#7cf994]/35 px-3 py-1 text-xs font-semibold text-[#005320]">{employee.status}</span></td></tr>)}</tbody></table>{!data.length && <EmptyState title="No employees" body="Add employees individually or use the bulk import wizard." />}</Panel>}</AdminPage>;
}

export function EmployeeEditorView() {
  const router = useRouter(); const [departments, setDepartments] = useState<Department[]>([]); const [designations, setDesignations] = useState<Designation[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState({ employeeCode: "", fullName: "", phone: "", workType: "OFFICE", dateOfJoining: new Date().toISOString().slice(0, 10), deptId: "", designationId: "" });
  useEffect(() => { Promise.all([apiClient.get("/departments"), apiClient.get("/designations?limit=100"), apiClient.get("/employees/next-code")]).then(([departmentResult, designationResult, codeResult]) => { setDepartments(departmentResult.data.data); setDesignations(designationResult.data.data); setForm((value) => ({ ...value, employeeCode: codeResult.data.data?.employeeCode ?? codeResult.data.employeeCode ?? "" })); }).catch(() => setError("Employee form options could not be loaded.")); }, []);
  async function save() { await apiClient.post("/employees", { ...form, phone: form.phone || undefined, designationId: form.designationId || undefined }).then(() => router.push("/app/employees")).catch(() => setError("Employee could not be created. Review code, phone and organization fields.")); }
  return <AdminPage title="Add Employee" description="Create a secure employee record and reporting placement." action={<PrimaryButton onClick={save}>Create employee</PrimaryButton>}>{error && <ErrorState message={error} />}<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><Panel className="p-7"><div className="grid gap-5 sm:grid-cols-2"><Field label="Employee code"><input className={inputClass} value={form.employeeCode} onChange={(e) => setForm({ ...form, employeeCode: e.target.value })} /></Field><Field label="Full name"><input className={inputClass} value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} /></Field><Field label="Phone"><input className={inputClass} placeholder="+919876543210" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field><Field label="Date of joining"><input type="date" className={inputClass} value={form.dateOfJoining} onChange={(e) => setForm({ ...form, dateOfJoining: e.target.value })} /></Field><Field label="Department"><select className={inputClass} value={form.deptId} onChange={(e) => setForm({ ...form, deptId: e.target.value })}><option value="">Select department</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></Field><Field label="Designation"><select className={inputClass} value={form.designationId} onChange={(e) => setForm({ ...form, designationId: e.target.value })}><option value="">No designation</option>{designations.map((designation) => <option key={designation.id} value={designation.id}>{designation.name}</option>)}</select></Field><Field label="Work type"><select className={inputClass} value={form.workType} onChange={(e) => setForm({ ...form, workType: e.target.value })}><option value="OFFICE">Office</option><option value="FIELD">Field</option><option value="HYBRID">Hybrid</option></select></Field></div></Panel><Panel className="p-7"><div className="grid size-14 place-items-center rounded-xl bg-[#e2dfff] text-[#3525cd]"><ShieldCheck /></div><h2 className="mt-5 font-semibold">Device & identity</h2><p className="mt-2 text-sm text-[#777587]">Device binding and face enrollment become available after the employee accepts their account invitation.</p></Panel></div></AdminPage>;
}

export function EmployeeImportView() {
  const [jobs, setJobs] = useState<Array<{ id: string; filename: string; status: string; totalRows: number; successRows: number; errorRows: number }> | null>(null); const [error, setError] = useState("");
  const load = () => apiClient.get("/employee-imports").then(({ data }) => setJobs(data.data)).catch(() => setError("Import history could not be loaded.")); useEffect(() => { void load(); }, []);
  async function upload(file: File) { try { const contentType = file.type || "text/csv"; const presign = await apiClient.post("/employee-imports/presign", { filename: file.name, contentType, fileSize: file.size }); await fetch(presign.data.uploadUrl, { method: "PUT", headers: { "Content-Type": contentType }, body: file }); await apiClient.post("/employee-imports", { filename: file.name, contentType, fileSize: file.size, objectKey: presign.data.objectKey }); load(); } catch { setError("Employee CSV could not be uploaded or validated."); } }
  return <AdminPage title="Bulk Import" description="Upload employees with safe row-level validation and idempotent retries.">{error && <ErrorState message={error} />}<Panel className="grid min-h-64 place-items-center border-2 border-dashed border-[#c7c4d8] p-8 text-center"><div><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-[#e2dfff] text-[#3525cd]"><FileUp /></div><h2 className="mt-5 text-xl font-semibold">Drop your employee CSV here</h2><p className="mt-2 text-sm text-[#777587]">CSV up to 5 MB. Errors remain visible without exposing sensitive data.</p><label className="mt-5 inline-flex h-11 cursor-pointer items-center rounded-xl bg-[#3525cd] px-5 text-sm font-semibold text-white">Choose CSV<input type="file" accept=".csv" className="hidden" onChange={(e) => e.target.files?.[0] && upload(e.target.files[0])} /></label></div></Panel><div className="mt-6">{!jobs ? <LoadingState /> : <Panel className="overflow-hidden">{jobs.map((job) => <div key={job.id} className="grid grid-cols-[1fr_120px_220px] items-center border-b border-[#e4e1ee] px-6 py-4 last:border-0"><div><div className="font-semibold">{job.filename}</div><div className="text-xs text-[#777587]">{job.totalRows} rows</div></div><span className="text-sm font-medium">{job.status}</span><div className="text-xs"><span className="text-[#006e2d]">{job.successRows} imported</span> · <span className="text-[#ba1a1a]">{job.errorRows} errors</span></div></div>)}{!jobs.length && <EmptyState title="No import history" body="Completed and failed imports will appear here." />}</Panel>}</div></AdminPage>;
}

export function UsersRolesView() {
  const [users, setUsers] = useState<User[] | null>(null); const [roles, setRoles] = useState<Role[]>([]); const [error, setError] = useState(""); const [inviteOpen, setInviteOpen] = useState(false); const [inviteEmail, setInviteEmail] = useState(""); const [inviteRoleIds, setInviteRoleIds] = useState<string[]>([]); const [sent, setSent] = useState(false);
  const load = () => Promise.all([apiClient.get("/users?limit=100"), apiClient.get("/roles")]).then(([userResult, roleResult]) => { setUsers(userResult.data.data); setRoles(roleResult.data.data); }).catch(() => setError("Users and roles could not be loaded."));
  useEffect(() => { void load(); }, []);
  async function invite() { setError(""); setSent(false); try { await apiClient.post("/users/invitations", { email: inviteEmail, roleIds: inviteRoleIds }); setSent(true); setInviteEmail(""); setInviteRoleIds([]); } catch { setError("Invitation could not be sent. Check the email, role, or an existing pending invitation."); } }
  return <AdminPage title="Users & Roles" description="Invite administrators and enforce least-privilege access." action={<PrimaryButton onClick={() => { setInviteOpen(true); setSent(false); }}><Plus className="size-4" />Invite user</PrimaryButton>}>{error && <ErrorState message={error} />}{!users ? <LoadingState /> : <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Panel className="overflow-hidden"><div className="border-b border-[#e4e1ee] bg-[#f5f2ff] px-6 py-4 font-semibold">Workspace users</div>{users.map((user) => <div key={user.id} className="flex items-center justify-between border-b border-[#e4e1ee] px-6 py-4 last:border-0"><div><div className="font-semibold">{user.email}</div><div className="text-xs text-[#777587]">{user.roles.map((role) => role.name).join(", ") || "No role"}</div></div><span className="rounded-full bg-[#7cf994]/35 px-3 py-1 text-xs font-semibold text-[#005320]">{user.status}</span></div>)}</Panel><Panel className="p-6"><h2 className="mb-4 font-semibold">Roles</h2><div className="grid gap-3">{roles.map((role) => <Link key={role.id} href={`/app/access/roles/${role.id}`} className="flex items-center justify-between rounded-lg border border-[#e4e1ee] p-4 hover:border-[#3525cd]"><div><div className="font-semibold">{role.name}</div><div className="text-xs text-[#777587]">{role.isSystem ? "System role" : "Custom role"} · {role.assignedUsers ?? 0} users</div></div><ShieldCheck className="size-5 text-[#3525cd]" /></Link>)}</div></Panel></div>}{inviteOpen && <AccessDialog title="Invite workspace user" onClose={() => setInviteOpen(false)}>{sent ? <div className="rounded-xl bg-[#d8f8df] p-5 text-sm text-[#005320]">Invitation created successfully. Delivery is handled by the configured notification provider.</div> : <div className="grid gap-4"><Field label="Work email"><input type="email" className={inputClass} value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} /></Field><fieldset className="grid gap-2"><legend className="mb-2 text-sm font-medium">Roles</legend>{roles.map((role) => <label key={role.id} className="flex items-center gap-3 rounded-lg bg-[#f5f2ff] p-3 text-sm"><input type="checkbox" checked={inviteRoleIds.includes(role.id)} onChange={(event) => setInviteRoleIds((current) => event.target.checked ? [...current, role.id] : current.filter((id) => id !== role.id))} />{role.name}</label>)}</fieldset><PrimaryButton disabled={!inviteEmail || !inviteRoleIds.length} onClick={invite}>Send invitation</PrimaryButton></div>}</AccessDialog>}</AdminPage>;
}

export function RoleEditorView({ roleId }: { roleId: string }) {
  const [role, setRole] = useState<Role | null>(null); const [catalog, setCatalog] = useState<Array<{ module: string; keys: string[] }>>([]); const [selected, setSelected] = useState<Set<string>>(new Set()); const [error, setError] = useState("");
  useEffect(() => { Promise.all([apiClient.get(`/roles/${roleId}`), apiClient.get("/permissions")]).then(([roleResult, catalogResult]) => { const value = roleResult.data.data as Role; setRole(value); setCatalog(catalogResult.data.data); setSelected(new Set(value.permissionKeys ?? [])); }).catch(() => setError("Role permissions could not be loaded.")); }, [roleId]);
  async function save() { setError(""); await apiClient.put(`/roles/${roleId}/permissions`, { permissionKeys: [...selected] }).then(({ data }) => setRole(data.data)).catch(() => setError("Permission matrix could not be saved.")); }
  return <AdminPage title={role?.name || "Role Editor"} description="Select the exact permission keys granted to this role." action={<PrimaryButton onClick={save}>Save permissions</PrimaryButton>}>{error && <ErrorState message={error} />}{!role ? <LoadingState /> : <Panel className="overflow-hidden">{catalog.map((group) => <div key={group.module} className="border-b border-[#e4e1ee] p-6 last:border-0"><h2 className="mb-4 text-sm font-bold uppercase tracking-wider text-[#3525cd]">{group.module}</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{group.keys.map((key) => <label key={key} className="flex items-start gap-3 rounded-lg bg-[#f5f2ff] p-3 text-sm"><input type="checkbox" className="mt-1 accent-[#3525cd]" checked={selected.has(key)} disabled={role.isSystem} onChange={(event) => setSelected((current) => { const next = new Set(current); if (event.target.checked) next.add(key); else next.delete(key); return next; })} /><span>{key}</span></label>)}</div></div>)}</Panel>}</AdminPage>;
}

function AccessDialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#1b1b24]/45 p-4"><div className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-2xl bg-white p-7 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={onClose} className="text-sm text-[#777587]">Close</button></div>{children}</div></div>; }
