export type InvoicePdfModel = {
  invoiceNumber: string;
  issuedOn: string;
  dueOn: string;
  sellerName: string;
  sellerGstin?: string | null;
  customerName: string;
  customerGstin?: string | null;
  currency: string;
  subtotal: string;
  cgst: string;
  sgst: string;
  igst: string;
  total: string;
  description: string;
  quantity: string;
  unitAmount: string;
};

export function renderInvoicePdf(model: InvoicePdfModel): Buffer {
  const lines = [
    'TAX INVOICE',
    `Invoice: ${model.invoiceNumber}`,
    `Issued: ${model.issuedOn}    Due: ${model.dueOn}`,
    `Supplier: ${model.sellerName}`,
    `Supplier GSTIN: ${model.sellerGstin || 'Not registered'}`,
    `Bill to: ${model.customerName}`,
    `Customer GSTIN: ${model.customerGstin || 'Not registered'}`,
    '',
    `${model.description} | Qty ${model.quantity} | Unit ${model.currency} ${model.unitAmount}`,
    `Subtotal: ${model.currency} ${model.subtotal}`,
    `CGST: ${model.currency} ${model.cgst}`,
    `SGST: ${model.currency} ${model.sgst}`,
    `IGST: ${model.currency} ${model.igst}`,
    `Total: ${model.currency} ${model.total}`,
    '',
    'Generated by DeltCRM. This immutable document matches the stored billing snapshot.',
  ];
  const stream = lines
    .map((line, index) => {
      const y = 790 - index * 25;
      const size = index === 0 ? 18 : 10;
      return `BT /F1 ${size} Tf 48 ${y} Td (${escapePdf(line)}) Tj ET`;
    })
    .join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let body = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(body));
    body += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(body);
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  body += offsets
    .slice(1)
    .map((offset) => `${offset.toString().padStart(10, '0')} 00000 n \n`)
    .join('');
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  return Buffer.from(body, 'utf8');
}

function escapePdf(value: string) {
  return value
    .normalize('NFKD')
    .replace(/[^\x20-\x7e]/g, '')
    .replace(/([\\()])/g, '\\$1');
}
